apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  AWS_ACCESS_KEY_ID: "${KUBERNETES_SECRET_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${KUBERNETES_SECRET_AWS_SECRET_ACCESS_KEY}"
