apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-ms
  template:
    metadata:
      labels:
        app: auth-ms
    spec:
      imagePullSecrets:
        - name: aws-credentials
      containers:
        - name: auth-ms
          image: 127214175530.dkr.ecr.ap-southeast-1.amazonaws.com/ms/auth-service:latest
          ports:
            - containerPort: 3000