apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-ms
  ports:
    - protocol: TCP
      port: 4000        # Service port
      targetPort: 3000  # Container port
      nodePort: 30040 # Exposed port on minikube node (can be between 30000-32767)
